//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassLoaderBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MassLoaderBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #r3UUErAh0dXW43ERRWPAAaEVY9aH5/OTsWHRxUbjYNAUcrCE9/OTsWHRxUbjYNAUcrCFoxXCIJERFHJwoaAR0JABoXQScGT385OxYdHFRuNg0BRysIWjZaLwIaHUA6DBcBCENvAQFaIAJUIUo9EREfHQcqT385OxYdHFRuNg0BRysIWjxWOl55eEY9DBoVEx0cBwZWI0s6F0dgNhERRjwMAAsIQ28BAVogAlQhSj0RER8dHAASHlYtER0dXXVofgdAJwsTUmA3FgAXXmA3ARxHJwgRXHAhCAQbXysXJxdBOAwXF0B1aH4HQCcLE1JgNxYAF15gNwEcRycIEVx6IBERAFw+NhEARScGEQEIQ28BAVogAlQhSj0RER8dHQAXB0EnEQ1ccDwcBAZcKRcVAls3SyxHA3cmEQBHJwMdEVI6AAdJPkQQBxtdKUUnC0A6ABlcZyYXERNXJwsTST5EEAcbXSlFJwtAOgAZXGcmFxETVycLE1xnLxYfAQhDb3l4E [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Error_Build {
            get {
                return ResourceManager.GetStream("Error_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream GoodBuild {
            get {
                return ResourceManager.GetStream("GoodBuild", resourceCulture);
            }
        }
    }
}
